import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import SmoothScroll from "./smooth-scroll";

import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/layout/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-heading",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Future Axis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"  suppressHydrationWarning>
      {/* <body
        
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <SmoothScroll>{children}</SmoothScroll>
        </ThemeProvider>
      </body> */}

      <body
  className={`${inter.variable} ${poppins.variable} antialiased min-h-screen flex flex-col`}
>
  <ThemeProvider
    attribute="class"
    defaultTheme="system"
    enableSystem
    disableTransitionOnChange
  >
    <Navbar />

    {/* MAIN CONTENT */}
      <SmoothScroll>
    <main className="flex-1">
        {children}
    </main>
    <Footer />
      </SmoothScroll>

    {/* FOOTER */}
    {/* 👇 Add here */}
    {/* import Footer first */}
    
  </ThemeProvider>
</body>
    </html>
  );
}
